### ISSUE TITLE
Need a way to make a single service

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-platform#10]
A couple times the `make` command failed during the `reaction` stuff due to Docker issues. I'm now only missing the starter kit, but the only way to get it is to rerun entire `make`, which takes forever and does stuff I don't need done again. The workaround is to remove some services from the list in the `Makefile`, but we should provide a simple way to do this.

This will also come up when updating the repo and then wanting to clone and build some new service that was added without rebuilding all of the existing.

**Comment by aldeed** [comment]
cc @ticean

**Comment by ticean** [comment]
It's [already supported](https://github.com/reactioncommerce/reaction-platform/commit/1c601cfd29b1278315fb986014b2655fd658274d).

**Comment by aldeed** [comment]
If it's not in the docs then it doesn't exist. 😄

**Comment by aldeed** [comment]
I added it to the readme now
