### ISSUE TITLE
[3.0.0] Leakage between .env files when running `make init`

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction-platform#100]
Creating here per request from @aldeed 

When running `make init` for the first time is tries to create .env file in each of the child projects, but the .env file it creates contains all the env values for all the projects not just each respective project. This doesn't cause a ton of problems since most of these are unique per project but for admin and identity they both use the `ROOT_URL` and it gets set to whatever the last value was and so the project doesn't start

It also fills these files with a ton of irrelevant values.

The workaround is to simple delete the `.env` file in each project and run `bin/setup` in each project and it creates the file just fine.

**Comment by aldeed** [comment]
@focusaurus @rosshadden @ticean Maybe one of you has some idea here

**Comment by rosshadden** [comment]
I fixed this in some repositories ( https://github.com/reactioncommerce/reaction/pull/5853 for example). It requires a per-project fix in the `bin/setup` file, so there may still be some projects that do not have the fix.

**Comment by aldeed** [comment]
Great then we just need to copy that into the other default platform projects. I'll add this to the 3.0 project list.

**Comment by aldeed** [comment]
Only `reaction-identity` project didn't have this fix and I've fixed that in https://github.com/reactioncommerce/reaction-identity/pull/23/commits/8bb012d0cde0cab083238a5b4399f37be70088ad
