### ISSUE TITLE
Can't insert product

### ISSUE THREAD

**Issue by serdarejepov** [reactioncommerce/reaction-platform#111]
I setup reactioncommerce successfully. All needed platforms for this have been installed. However when I want to insert tags and products via admin panel, it gives error. When I reload the page, products added without any data. 

Can I help or guide me on how to go in right direction?

**Comment by manueldelreal** [comment]
there was an issue with the `reaction-admin` similar to this for the very first created product but I believe that has been resolved for the past two releases. I tried for both tags and products on the current tagged versions for all components of platform and I can successfully create them locally. 

We do have some test environments where I'm seeing a similar behavior but just for products, I'll investigate there to rule out configuration issues and open an issue in https://github.com/reactioncommerce/reaction-admin if that's not the case. 

I'm closing this one meanwhile as it not a platform issue per se. Thanks for the report.
