### ISSUE TITLE
Installation run successfully but nothing seems to be working

### ISSUE THREAD

**Issue by carlosconnected** [reactioncommerce/reaction-platform#127]
Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [:heavy_check_mark:] Are you running the latest version?
* [:heavy_check_mark:] Are you able to consistently reproduce the issue?
* [:heavy_check_mark:] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
I followed the instructions to run reaction commerce using the make file. I did not get any error when I run the make file. However, nothing seems to be working.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. `git clone git@github.com:reactioncommerce/reaction-development-platform.git`
2. `cd reaction-development-platform`
3. `make`
4. Try to access http://localhost:4080 or http://localhost:4000, but they don't exist
5. But the ports are getting run by docker
![image](https://user-images.githubusercontent.com/1195403/80961446-331a6480-8e35-11ea-9921-f09443536b9d.png)

## Possible Problem
1. `cd reaction`
2. `docker-compose logs -f api
3. See logs
![image](https://user-images.githubusercontent.com/1195403/80960736-a4f1ae80-8e33-11ea-9517-d9298d7b067c.png)

### Versions
- Branch: release-next-v3.7.0
- Release 3.4.0
- Runnin on MacOS 10.15.4 (Catalina)

**Comment by sterowney** [comment]
I had the same problem, so I ran the local version of reaction-api. (Docker image shipped didn't contain plugins.json file, so couldn't find api-core dependency) 

I first stopped the docker container 
`make stop-reaction`

I ran npm install in the reaction directory

`make clean-reaction` & `make dev-link-reaction` 

Then `make start-reaction`

Works now, hope this helps you, or someone else who finds this.

**Comment by carlosconnected** [comment]
Thanks @sterowney! Very similar to what I ended up doing:
`make dev-link-reaction && docker stop reaction_api_1 && make start-reaction`
