### ISSUE TITLE
Fails at "Creating development OAuth clients for reaction-hydra"

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction-platform#13]
## Issue Description
I cloned reaction-platform and ran the makefile as described.
The process gets stuck while creating the hydra client with:

> Command failed because calling " http://hydra.auth.reaction.localhost:4445/clients" resulted in error "Post http://hydra.auth.reaction.localhost:4445/clients: dial tcp 172.23.0.2:4445: connect: no route to host" occurred.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Clone the Repo
2. Run make
3. Oberserve that it fails at the described point.

## Possible Solution
Is additional docker configuration necessary that was not described in the readme?

**Comment by ticean** [comment]
Hi @janus-reith, thanks for reporting the issue. Could you run a few commands and paste results to provide more information your system status?

1. `docker network ls` - List your Docker networks. Just checking that all the networks are there, though I don't think you would have made it this far without them. (You can remove output that's not `*.reaction.localhost` if you'd like.)
2. `docker ps -a` - List the status of the Reaction Docker containers. (You can remove output for non-reaction containers if you'd like.)
3. `docker logs reaction-hydra_hydra_1` - That should match the default container name for the Hydra container. We're looking for the logs from Hydra to make sure it started correctly.

**Comment by janus-reith** [comment]
Thanks for the detailed response!

`docker network ls` (I removed some in that list that are not relevant to the project):
```
6338014bdffa        api.reaction.localhost     bridge              local
39ec2ec63f00        auth.reaction.localhost    bridge              local
b4fc8eaccb5f        bridge                     bridge              local
508d3d0b32f6        dump_default               bridge              local
5e03c653ff3f        host                       host                local
29f1ae447de3        none                       null                local
ffb80b601130        reaction-api               bridge              local
2cf2882e027f        reaction-hydra_default     bridge              local
44747ff2fd29        reaction_default           bridge              local

```

`docker ps -a | grep reaction`
```
12532ebd3d2a        reaction_devserver                "bash -c 'echo 'Star…"    2 minutes ago       Exited (1) 51 seconds ago                                                               reaction_devserver_1
a5c80ae70022        mongo:3.6.3                       "docker-entrypoint.s…"    2 minutes ago       Up 2 minutes                 0.0.0.0:27017->27017/tcp                                   reaction_mongo_1
e115cfffc14a        reaction-next-starterkit_web      "sh -c 'yarn install…"    2 days ago          Exited (1) 2 days ago                                                                   reaction-next-starterkit_web_1
63869dd2c672        oryd/hydra:v1.0.0-beta.9-alpine   "hydra serve all --d…"    2 days ago          Up About a minute            0.0.0.0:4444-4445->4444-4445/tcp, 0.0.0.0:5555->5555/tcp   reaction-hydra_hydra_1
0d1560f0293b        oryd/hydra:v1.0.0-beta.9-alpine   "hydra migrate sql -e"    2 days ago          Up 29 seconds                                                                           reaction-hydra_hydra-migrate_1
5e9576b75b9c        postgres:10.3                     "docker-entrypoint.s…"    2 days ago          Up 2 days                    0.0.0.0:32769->5432/tcp                                    reaction-hydra_postgres_1
```

`docker logs reaction-hydra_hydra_1`

> Thank you for using ORY Hydra v1.0.0-beta.9!
> 
> Take security seriously and subscribe to the ORY Security Newsletter. Stay on top of new patches and security insights.                                                                                                
> 
> Subscribe now: http://eepurl.com/di390P <<
> time="2018-09-30T17:24:21Z" level=info msg="Connecting with postgres://*:*@postgres:5432/hydra?sslmode=disable"
> time="2018-09-30T17:24:22Z" level=info msg="Unable to connect to database" error="Could not Connect to SQL: dial tcp 172.25.0.2:5432: connect: no route to host"
> time="2018-09-30T17:24:22Z" level=info msg="Retrying in 0.100000 seconds..."
> time="2018-09-30T17:24:22Z" level=info msg="Connecting with postgres://*:*@postgres:5432/hydra?sslmode=disable"
> time="2018-10-01T07:53:15Z" level=info msg="Unable to connect to database" error="Could not Connect to SQL: dial tcp 172.25.0.2:5432: connect: no route to host"
> time="2018-10-01T07:53:15Z" level=info msg="Retrying in 0.200000 seconds..."

This repeats several times without succesful connect - I'm wondering if this could be related to my firewall configuration(running on Arch with firewalld) If that's the case then this would probably not be an issue with the project.

Output of `create-clients.sh` (seems to be similar to the error thrown during make)
```
Operation timed out
You should not provide secrets using command line flags. The secret might leak to bash history and similar systems.
ERROR: creating hydra client
Command failed because calling " http://hydra.auth.reaction.localhost:4445/clients" resulted in error "Post http://hydra.auth.reaction.localhost:4445/clients: dial tcp 172.23.0.2:4445: connect: no route to host" occurred.

```

**Comment by ticean** [comment]
> This repeats several times without succesful connect - I'm wondering if this could be related to my firewall configuration(running on Arch with firewalld) If that's the case then this would probably not be an issue with the project.

This could be the case. @janus-reith could you try temporarily modifying your firewall rules to see if it resolves?

We have a few folks running on Linux but we're generally running on OSX and using Docker for Mac. I'm personally on a Mac. In Docker for Mac, internal networks are running inside an isolated Docker host and unaffected by Mac host level networking rules. I could see this being different in your case.

Have you seen this information?
https://wiki.archlinux.org/index.php/docker#Running_Docker_with_a_manually-defined_network_on_systemd-networkd

**Comment by ticean** [comment]
After another read, it does look like some kind of networking issue. The logs show an issue between the `hydra` and `postgres` services. That's straighforward Docker Compose networking and I would expect no problems there at all. You can see that the Hydra service is retrying to connect to Postgres.

Let me know if you can get it working and we can add notes to the troubleshooting guide.

---

I've received internal report of a separate race condition that results in this same outward error. I originally thought that this was related, but it does look to be different. We should have a fix for that one soon. FYI, in case you get networking resolved and hit the race issue again. :)

**Comment by janus-reith** [comment]
Okay, closing this as it was related to firewalld.
I thought I opened up the necessary ports there, and need to investigate further, but stopping it made this work.

**Comment by focusaurus** [comment]
@janus-reith thanks for this follow up. I'll add this to the common issues document so others might find a solution there.
