### ISSUE TITLE
Error on reaction-admin MongoError: not master and slaveOk=false

### ISSUE THREAD

**Issue by apaajabolehd** [reactioncommerce/reaction-platform#132]
Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [ yes ] Are you running the latest version?
* [ yes ] Are you able to consistently reproduce the issue?
* [ yes ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Providing a clear description of the issue will enable a developer to quickly reproduce and understand the issue. Please provide a detailed description including images, animation and/or videos. For client issues, include browser console errors, for server issues please add terminal output and stack traces.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. follow the docs for the installation
2. run make start
3. login to admin page and open any page with listing, there is an error on the console 
"Uncaught (in promise) Error: GraphQL error: Access Denied"

when I tried to log the reaction-admin I got these errors 
"Exception from sub Accounts id 57jPc8aeXwuSkhExr TypeError: Cannot read property 'some' of undefined"
"Exception from sub Accounts id PP4hRmCFhmvNRSwAa TypeError: Cannot read property 'some' of undefined"
"MongoError: not master and slaveOk=false"

**Comment by focusaurus** [comment]
Could you try to restart the reaction api with:

```sh
cd reaction
docker-compose restart
```

It looks like some of our mongodb replica set configuration may not have succeeded, but it runs every time the API server starts so that may fix it.

**Comment by apaajabolehd** [comment]
still not fixed it, I already tried restart all server, and each server 1 by 1, still no luck.
I have updated my question with the complete error on reaction-admin logs.

**Comment by focusaurus** [comment]
Investigating. I wrote code specifically to handle this issue but that code seems to have moved or been removed in https://github.com/reactioncommerce/reaction/commit/0f9fef20fb50087b51fb74c23e8608f4e7a246ac

Trying to track down where it landed and add it back if it's just deleted.

**Comment by focusaurus** [comment]
OK the `waitForMongo.js` script that handles this is now in both `reaction-identity` and `reaction-admin` but no longer in `reaction`. When either of identity or admin start up they should get mongodb into the right state and once that's done everything should be able to connect to mongo properly.

Could you try this please from your reaction-development-platform directory?

1. ensure mongo is up with `docker-compose -f reaction/docker-compose.yml up -d`
2. confirm that with `docker-compose -f reaction/docker-compose.yml logs mongo`
3. bring up identity with `docker-compose -f reaction-identity/docker-compose.yml restart`
4. Watch the logs for `Wating for MongoDB...` `docker-compose -f reaction-identity/docker-compose.yml logs`

If all's well you'll see logs like this:

```
identity_1  | Waiting for MongoDB...
identity_1  | MongoDB ready.
identity_1  | Waiting for MongoDB replica set...
identity_1  | MongoDB replica set ready.
identity_1  | 16:37:24.575Z  INFO Reaction: Serving Reaction Identity at http://localhost:4100
```

**Comment by focusaurus** [comment]
One other thing you might try:

```
 docker-compose -f reaction/docker-compose.yml exec mongo mongo --eval 'rs.slaveOk()'
```

**Comment by focusaurus** [comment]
OK I actually got into this situation myself on my linux laptop just now. I think its a race condition between startup of mongo and identity or admin. I'm confident my above [comment](https://github.com/reactioncommerce/reaction-development-platform/issues/132#issuecomment-638971388) instructions will get you sorted. Please reopen if you are still stuck.
