### ISSUE TITLE
Operator UI

### ISSUE THREAD

**Issue by mamged** [reactioncommerce/reaction-platform#138]
Hi,
I executed all the steps found here [https://docs.reactioncommerce.com/docs/installation-reaction-platform](https://docs.reactioncommerce.com/docs/installation-reaction-platform)
but there is something I don't understand: "Note: To login into the Operator UI use the credentials found in the [env.example](https://github.com/reactioncommerce/reaction/blob/v2.9.1/.env.example#L11-L12) file." what do you mean by "Operator UI"? where can exactly can I use the mentioned credentials.

**Comment by mamged** [comment]
I normally registered an account and can access admin UI, but still not sure where can I use these credentials.

**Comment by focusaurus** [comment]
I believe that is referring to "Reaction Admin" which is at http://localhost:4080. You can log in there with the first user you created when you first launched the platform with an empty database. The same credentials should work in the example storefront as well.

**Comment by mamged** [comment]
@focusaurus I can use my first account as admin it's working fine, but I'm also trying to use this user: admin@localhost & pass: r3@cti0n as mentioned but I get `User not found [403]`.
I guess this is bug or documentations needs to be updated [here](https://docs.reactioncommerce.com/docs/installation-reaction-platform). I'm closing this here.

**Comment by focusaurus** [comment]
@mAmged Yeah I think thats stale documentation. We used to create a default account automatically on startup with a configured email/password from .env, but it recently changed to no users by default and first registration becomes the first administrator. I'll file a doc bug to get this clear up. Thanks!
