### ISSUE TITLE
Are you running the latest version? --maybe

### ISSUE THREAD

**Issue by ghost** [reactioncommerce/reaction-platform#158]
Most of the issue templates ask the titled question which doesn't actually tell us a whole lot given the number of moving pieces in the stack. Additionally the question isn't timeless given `latest` today won't mean much to someone debugging an issue tomorrow.

Please introduce a script akin to `reaction -v` that gives maintainers and users an easy way to report their current stack configuration. Then, in issue templates, request that information instead of asking if the user is running the latest version.

**Comment by delagroove** [comment]
merged in latest dev-platform PR
