### ISSUE TITLE
Automation for the release process

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction-platform#167]
## Issue Description
Automate the process of creating release branches, creating PRs, pushing to docker and finally doing a release on github.

**Comment by balibebas** [comment]
> Automate the process of creating release branches, creating PRs, pushing to docker and finally doing a release on github.

Suggest not relying on GH at all for the release process. Please ensure any automation is git provider agnostic. User may be using GitLab, sr.ht, gitea, and who knows what in the future.
