### ISSUE TITLE
Could not connect to Hydra service at http://hydra.reaction.localhost:4445

### ISSUE THREAD

**Issue by claptonorioste** [reactioncommerce/reaction-platform#175]
Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
 [yes ] Are you running the latest version?
 [ yes] Are you able to consistently reproduce the issue?
 [ yes] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. clone latest version
2. make
## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

**Comment by Akarshit** [comment]
@claptonorioste Thanks for reporting this. Because of a unintentional merge, the trunk branch was broken.
This should be fixed in a few hours with #177, but if you want to try something right now that PR should be the one to try.

Again apologies for the bad experience.
