### ISSUE TITLE
Wrong reaction docker image version

### ISSUE THREAD

**Issue by ZappaBoy** [reactioncommerce/reaction-platform#185]
## Prerequisites
* [X] Are you running the latest version?
* [X] Are you able to consistently reproduce the issue?
* [X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Following the installation instruction there is an error about the reaction docker version (manifest not exists):
```
~ make 
Error response from daemon: network with name reaction.localhost already exists
Removed docker development symlink for reaction-hydra
Running pre-build hook script for reaction-hydra.
reaction-hydra post-project-start script invoked.
postgres uses an image, skipping
hydra-migrate uses an image, skipping
hydra uses an image, skipping
Running post-build hook script for reaction-hydra.
reaction-hydra post-build script invoked.
Pulling postgres      ... done
Pulling hydra-migrate ... done
Pulling hydra         ... done
Creating network "reaction-hydra_default" with the default driver
Creating volume "reaction-hydra_postgres-data" with default driver
Creating reaction-hydra_postgres_1 ... done
Creating reaction-hydra_hydra-migrate_1 ... done
Creating reaction-hydra_hydra_1         ... done
Running post-project-start hook script for reaction-hydra.
reaction-hydra post-project-start script invoked.
Removed docker development symlink for reaction
Running pre-build hook script for reaction.
reaction post-project-start script invoked.
mongo uses an image, skipping
api uses an image, skipping
Running post-build hook script for reaction.
reaction post-build script invoked.
Pulling mongo ... done
Pulling api   ... error

ERROR: for api  manifest for reactioncommerce/reaction:3.13.0 not found: manifest unknown: manifest unknown
ERROR: manifest for reactioncommerce/reaction:3.13.0 not found: manifest unknown: manifest unknown
Creating network "reaction_default" with the default driver
Creating volume "reaction_mongo-db4" with default driver
Pulling api (reactioncommerce/reaction:3.13.0)...
ERROR: manifest for reactioncommerce/reaction:3.13.0 not found: manifest unknown: manifest unknown
make: *** [Makefile:348: start-reaction] Error 1
```
Checking on dockerhub.com i noticed that his issues is due to the fact that there is no "reaction:3.13.0" docker image version. So i fixed it to the right latest version.
  
## Steps to Reproduce
1.  ```git clone https://github.com/reactioncommerce/reaction-development-platform.git```
2. ```cd reaction-development-platform```
3. ```make```

## Possible Solution
Replacing reaction docker image version from `reaction:3.13.0` to `reaction:3.13.1` in `./config.mk` and in `./reaction/docker-compose.yml`.

### Versions
Docker image versions: 
```shell 
reactioncommerce/example-storefront:4.0.2
reactioncommerce/identity:3.3.0
reactioncommerce/admin:3.0.0-beta.15
reactioncommerce/reaction:3.13.0 # (Need to be 3.13.1)
mongo:4.2.0
oryd/hydra:v1.0.8
oryd/hydra:v1.0.8
postgres:10.3
```
## Other comment
I tried to make a pull request with the changes but the contribution page not work so i preferred to only open this issues.

**Comment by jesusnazarethgh** [comment]
Hi.., same issue. Run `make update-checkouts` then `make`.

**Comment by jacobsenanaizabel** [comment]
this works for me! Thanks @ZappaBoy

**Comment by francolaiuppa** [comment]
Thanks @ZappaBoy! I ended up finding the same solution but in our case, it worked using `3.12.0`. Clearly using the latest version it's better.

**Comment by Akarshit** [comment]
Thanks for reporting this. I will fix this ASAP.

**Comment by Akarshit** [comment]
We have released a new version that should have this fixed.
