### ISSUE TITLE
Question: How to find make command on Windows?

### ISSUE THREAD

**Issue by donhuvy** [reactioncommerce/reaction-platform#186]
https://mailchimp.com/developer/open-commerce/guides/quick-start/

![image](https://user-images.githubusercontent.com/1328316/126928455-e6aba781-7923-44f9-bca5-4aa7a3dfcda4.png)

(I also tried https://stackoverflow.com/questions/68523969/docker-run-inside-ubuntu-on-windows-wsl but not success)

Question: How to find make command on Windows?

**Comment by MohanNarayana** [comment]
@donhuvy you will have to install make. Try this [stackoverflow](https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows).
For further questions please use out community [discord](https://discord.com/channels/842420811360763936/842420812053086210).
As this is a question and not an issue I will close this. I encourage you to raise issues if you find any in the future.

**Comment by SaqlainYounas** [comment]
Use https://chocolatey.org/install to install Make on windows.

Running Reaction on windows will give you a lot of problems. I will recommend Using WSL and or simply install a VM and Ubuntu on it.

**Comment by MohanNarayana** [comment]
@donhuvy  We have created an [issue](https://github.com/reactioncommerce/docs/issues/8) to update the docs for windows.
