### ISSUE TITLE
Simplify make commands

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction-platform#191]
## Issue Description
We have tons of make commands that are overlapping. The structure is confusing(to me), so maybe we can move to things that are more simple.

## Possible Solution
We can have the following commands:
1. `make start <project-name?> <dev|prod>`, this will clone the repos if needed and then start them all in dev/prod mode. If project-name is specified, will only start that project in the requested mode.
2. `make stop <project-name?>`, this will stop the containers
3. `make restart <project-name?>`, restart in the same mode
4. `make clean  <project-name?>`, removes the containers, volumes etc.
5. `make rm <project-name?>`, removes the containers
6. `make link <project-name?>`, links a project in development mode.
7. `make unlink <project-name?>`, un-links a project.

**Comment by rondlite** [comment]
> * `make link <project-name?>`, links a project in development mode.
> * `make unlink <project-name?>`, un-links a project.

This might need some more clarification on the actual effect, as in what is the difference between `make start dev` and `make link`

**Comment by loan-laux** [comment]
>6. `make link <project-name?>`, links a project in development mode.
>7. `make unlink <project-name?>`, un-links a project.

I think the wording could be confused with the `bin/package-link` script... Maybe `make dev-on` and `make dev-off` instead or something of that sort?
