### ISSUE TITLE
navigation in dashboard not working

### ISSUE THREAD

**Issue by meiremans** [reactioncommerce/reaction-platform#198]
## Prerequisites
* [ X] Are you running the latest version?
* [ X] Are you able to consistently reproduce the issue?
* [ X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Following the quick start guide. (https://mailchimp.com/developer/open-commerce/guides/quick-start/)
I end up in the admin dashboard. when I press navigation the dasboard crashes. the console mentions : "Uncaught TypeError: this.clearMonitorSubscription is not a function"

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. follow the quick start guide to set up local server
2. go to admin dashboard
3. make a product
4. change language to Romanian and currency to EUR 
5. press on navigation

the dashboard will crash.

is there a fix for this? or did I do something wrong? 

Thank you

**Comment by delagroove** [comment]
@meiremans upgrade reaction-admin to beta-21
like in this PR
https://github.com/reactioncommerce/reaction-development-platform/pull/197
we have issues with collaborators that do not sign off their code. leaving it in limbo

**Comment by delagroove** [comment]
change has been merged into `trunk`, pull and try again
closing for now

**Comment by meiremans** [comment]
thanks for the quick reply, works now :)
