### ISSUE TITLE
Makefile:88: *** missing separator. Stop.

### ISSUE THREAD

**Issue by austinfrey** [reactioncommerce/reaction-platform#26]
Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [x ] Are you running the latest version?
* [x ] Are you able to consistently reproduce the issue?
* [x ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
There seems to be an issue that snuck into the Makefile. On a fresh clone of this repo, running `make` throws a `missing separator` error.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. run git clone on this repo
2. `cd reaction-platform && make`
3. throws error `Makefile:88: *** missing separator.  Stop.`

## Possible Solution
Rolling back to this commit `431fa827a7937d058056c7221fce4846e8742044`  fixes the issue for me. I researched and this error could be related to tabs vs spaces issue, but I'm unsure of the Makefile syntax so not sure how to debug.

**Comment by dhcrzf** [comment]
I encountered the same problem.

**Comment by focusaurus** [comment]
I think there's a syntax error in `config.mk`. Should have a PR shortly.

**Comment by austinfrey** [comment]
@focusaurus that did the trick for me. thanks for the quick response
