### ISSUE TITLE
fsevents@1.2.4 error

### ISSUE THREAD

**Issue by AaronZhangL** [reactioncommerce/reaction-platform#31]
[xxxx@localhost reaction-platform]$ cat /etc/redhat-release 
Fedora release 28 (Twenty Eight)
[xxxx@localhost reaction-platform]$ uname -r
4.16.3-301.fc28.x86_64

I got this error.
---------
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by Isolated-** [comment]
@AaronZhangL this isn't an error. It's a warning detailing that the package fsevents is being skipped. This is due to the fact that `fsevents` is a module targetting OSX (darwin) operating systems and isn't requried on linux.

This is expected and can be safely ignored.
