### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by kodermax** [reactioncommerce/reaction-platform#35]
![image](https://user-images.githubusercontent.com/590985/50790322-b2466980-12cf-11e9-8416-f04dd3d931d1.png)

**Comment by walkerblackwell** [comment]
You need a github acct w/ ssh key installed locally and online: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/ as it says in the ReadMe reqs.
