### ISSUE TITLE
syntax error: unexpected end of file

### ISSUE THREAD

**Issue by mrseanbaines** [reactioncommerce/reaction-platform#43]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
I am getting error `syntax error: unexpected end of file` when trying to install the latest version of reaction-commerce.

![image](https://user-images.githubusercontent.com/24367010/50995848-3854f100-1518-11e9-9cb1-ecabd55cd458.png)

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. `git clone git@github.com:reactioncommerce/reaction-platform.git`
2. `cd reaction-platform`
3. `make`

### Versions
docker@latest
reaction-commerce@latest

**Comment by spencern** [comment]
What OS are you running? 
I just pulled the latest and ran `make` and am unable to reproduce this issue.

**Comment by mrseanbaines** [comment]
@spencern macOS Mojave 10.14.2. Might it be that I am running Fish shell?

**Comment by mrseanbaines** [comment]
...actually I've just tried using Bash and am having the same issue.

**Comment by ekayy** [comment]
Getting the same thing on macOS Mojave 10.14.1

**Comment by spencern** [comment]
I've been able to confirm this now. Looking through recent code changes
