### ISSUE TITLE
containers unresponsive and then shuts down

### ISSUE THREAD

**Issue by andrewtch** [reactioncommerce/reaction-platform#49]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Reaction makes ok, starts containsers that consume ~200% cpu, then the load dissappears (~3-4 min). 4000 port keeps loading all the time, 3000 port just shuts down (refuses to connect).

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. make
2. try :3000 :4000

Meteor pooling interval still 10000. Latest Mojave, latest Docker, master.

**Comment by focusaurus** [comment]
Could you take a look at the output of `docker-compose -f reaction/docker-compose.yml logs`  and `docker-compose -f reaction-next-starterkit/docker-compose.yml logs` for error messages that might give us some idea what could be going wrong?

**Comment by adrienshen** [comment]
Second this. Tried running the entire suite on MBP with 8gb memory. Keeps loading and using up lots of cpu and memory. It takes too much resources to develop locally, so I'm trying to deploy part of the platform hosted somewhere, and then only run the next-starter-kit locally for developing the storefront. Is this an option and is there docs to explain this setup?

**Comment by andrewtch** [comment]
@adrienshen , it requires at least of 4-6 GB of RAM dedicated to Docker to run and ~ 10min to load. As for gitter, this is a normal behaviour. 

Closing as Reactions seems to be "slow by design".
