### ISSUE TITLE
make init-example-storefront doesn't seem to be working

### ISSUE THREAD

**Issue by BunnyMan1** [reactioncommerce/reaction-platform#64]
After using make in v2, I have tried using the command `make init-super-arts` in the reaction-platform directory. It is not working and shows an error `make: *** No rule to make target 'init-super-arts'.  Stop.`

Am I doing something wrong here? I think the Makerfile seems to be missing another .Phony tag at the 'init' command.

**Comment by jackson-sandland** [comment]
What is `super-arts1?
