### ISSUE TITLE
make shows reaction-identity repository missing

### ISSUE THREAD

**Issue by Escalion** [reactioncommerce/reaction-platform#84]
Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [Y ] Are you running the latest version?
* [ Y] Are you able to consistently reproduce the issue?
* [ Y] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Executing the 'make' command on a fresh clone of the repository results in a build error due to missing repository.

if [ ! -d "reaction-identity" ] ; then git clone "git@github.com:/reactioncommerce/reaction-identity.git" "reaction-identity"; cd reaction-identity && git checkout "v3.0.0-alpha"; fi
Cloning into 'reaction-identity'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. clone repo
2. change directory
3. run make

## Possible Solution
Identify cause of repository missing on github.

### Versions
master

**Comment by Escalion** [comment]
Issue is not reproducible on the release branch

**Comment by Mikhail-MM** [comment]
I am having this issue as well

**Comment by aol-nnov** [comment]
@Escalion it is reproducible on master though..

https://github.com/reactioncommerce/reaction-identity is showing 404 now

**Comment by metaory** [comment]
recently added by 
@rosshadden https://github.com/reactioncommerce/reaction-platform/commit/adfe7038fd5c9f417d711a6877afdf3ecd9948f0

reverting to previous https://github.com/reactioncommerce/reaction-platform/blob/2278d3d6a45dad95e076e0d1d555aa9c5a6ff276/config.mk
didnt solve the issue

:ambulance:

**Comment by thuanpq** [comment]
how come you guys can test on branch Master,

**Comment by Escalion** [comment]
reaction-identity is now available. closing the issue
