### ISSUE TITLE
[3.0.0] Example storefront and reaction admin fail to start with make

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-platform#89]
## Issue Description
`example-storefront` and `reaction-admin` fail to start when running `make` in the `release-v3.0.0` branch in a new directory for the first time.

[edit Dec 27, 2019 for clarity]
These containers fail after attempting to start the first time I run `make` in a new project. I can start them with make (e.g. `make-start-example-storefront`) once the Mongo and API containers are run.

```
Attaching to example-storefront_web_1
web_1  | Creating Hydra client...
web_1  | FetchError: request to http://hydra.auth.reaction.localhost:4445/clients failed, reason: getaddrinfo ENOTFOUND hydra.auth.reaction.localhost hydra.auth.reaction.localhost:4445
web_1  |     at ClientRequest.<anonymous> (/usr/local/src/app/node_modules/node-fetch/index.js:133:11)
web_1  |     at ClientRequest.emit (events.js:198:13)
web_1  |     at Socket.socketErrorListener (_http_client.js:392:9)
web_1  |     at Socket.emit (events.js:198:13)
web_1  |     at emitErrorNT (internal/streams/destroy.js:91:8)
web_1  |     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
web_1  |     at process._tickCallback (internal/process/next_tick.js:63:19)
example-storefront_web_1 exited with code 1
```
```
Attaching to reaction-admin_reaction-admin_1
reaction-admin_1  | /usr/local/src/app/programs/server/node_modules/fibers/future.js:313
reaction-admin_1  | 						throw(ex);
reaction-admin_1  | 						^
reaction-admin_1  |
reaction-admin_1  | MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo mongo:27017]
reaction-admin_1  |     at Pool.<anonymous> (/usr/local/src/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
reaction-admin_1  |     at emitOne (events.js:116:13)
reaction-admin_1  |     at Pool.emit (events.js:211:7)
reaction-admin_1  |     at Connection.<anonymous> (/usr/local/src/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
reaction-admin_1  |     at Object.onceWrapper (events.js:317:30)
reaction-admin_1  |     at emitTwo (events.js:126:13)
reaction-admin_1  |     at Connection.emit (events.js:214:7)
reaction-admin_1  |     at Socket.<anonymous> (/usr/local/src/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
reaction-admin_1  |     at Object.onceWrapper (events.js:315:30)
reaction-admin_1  |     at emitOne (events.js:116:13)
reaction-admin_1  |     at Socket.emit (events.js:211:7)
reaction-admin_1  |     at emitErrorNT (internal/streams/destroy.js:66:8)
reaction-admin_1  |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
reaction-admin_1  |     at process._tickCallback (internal/process/next_tick.js:181:9)
reaction-admin_reaction-admin_1 exited with code 1
```

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Clone `reaction-platform` into clean repository
2. run `make start`
3. Observe that `reaction-admin` and `example-storefront` fail to start.
  You can observe this by running `docker ps` or by `cd`ing into each directory and running `docker-compose logs -f` for each project to see the errors.

## Possible Solution
There may be a race condition between starting dependent services (Mongo, etc) and these services. 

### Versions
release-3.0.0

**Comment by aol-nnov** [comment]
Same here, but I'd like to add that example-storefront logs show the following:

```
================================
 Missing environment variables:
    OAUTH2_IDP_PUBLIC_CHANGE_PASSWORD_URL: undefined
    OAUTH2_PUBLIC_LOGOUT_URL: undefined

 Exiting with error code 1
================================
```

**Comment by aldeed** [comment]
@spencern Most likely our race condition and ENV fixes have resolved these issues. Do you want to confirm and close?

**Comment by aol-nnov** [comment]
@aldeed I'm not @spencern , but I've tried v3.0.0 tag and trunk branch, but `example-storefront_web_1` did not start and it has the following in the logs:
```
================================
 Missing environment variables:
    OAUTH2_IDP_PUBLIC_CHANGE_PASSWORD_URL: undefined
    OAUTH2_PUBLIC_LOGOUT_URL: undefined

 Exiting with error code 1
================================
```

Also, some docker networks were reported missing, so I had to create them by hand.

Here they are:
* api.reaction.localhost
* auth.reaction.localhost
* streams.reaction.localhost

**Comment by aldeed** [comment]
@aol-nnov As I commented in another issue, the two main things to do are:

1. Confirm you have latest `trunk` branch checked out in every subproject
2. Manually copy `.env.example` to `.env` in every subproject directory. (If you're upgrading in an existing platform directory, the `bin/setup` script only adds new variables and does not update existing ones.)
3. Potentially try the `make clean` command in platform directory followed by `make` to try again.

Or clone into an entirely new directory and run `make`

**Comment by aol-nnov** [comment]
> Confirm you have latest trunk branch checked out in every subproject

Indeed, it helped. I was hoping, that having latest trunk of reaction-platform is sufficient and the rest is done by the Makefile itself...

Just removed all subproject folders and run make and it finally worked, yay!

**Comment by aldeed** [comment]
@aol-nnov Glad to hear that. Makefile does not touch the projects if they are already cloned because people often need to check out specific branches for one or more of them. I'm sure we could improve the logging around that, though, so that it's clear what's running.

**Comment by MohanNarayana** [comment]
@spencern can we go ahead and close this issue. Looks like some [fixes](https://github.com/reactioncommerce/reaction/issues/6033) were implemented for this issue it does not persist anymore. Also, having worked on 4.0.0 I can confirm I did not encounter the same.

**Comment by spencern** [comment]
yep. let's close it out.
